---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: samba
  name: samba-controller
  namespace: compute-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: samba
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: samba
    spec:
      containers:
      - image: illallangi/samba-controller:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
        name: controller
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP
      serviceAccount: samba-controller
      serviceAccountName: samba-controller

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: samba
  name: samba-controller
  namespace: compute-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: samba
  name: samba-controller
rules:
- apiGroups:
  - controllers.illallangi.enterprises
  resources:
  - sambas
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - controllers.illallangi.enterprises
  resources:
  - dnsrpzrecord
  verbs:
  - create
  - get
  - list
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: samba
  name: samba-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: samba-controller
subjects:
- kind: ServiceAccount
  name: samba-controller
  namespace: compute-system